version: '3'
services:
  gatekeeper:
    build: ./
    container_name: gatekeeper
    restart: always
    volumes:
      - "./error.log:/app/error.log"
    environment:
      - TZ=Europe/Moscow
    logging:
      driver: json-file
      options:
        max-size: 50m 
