version: '3'
services:
  simple-file-transfer:
    build: ./
    container_name: simple-file-transfer
    restart: always
    environment:
      - TZ=Europe/Moscow
    logging:
      driver: json-file
      options:
        max-size: 50m 
